### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by sytelus** [byu-magicc/ROSflight#105]
Could you please add license file for the project? Hoping for MIT license so it can be included with other projects with MIT license such as [AirSim](https://github.com/microsoft/airsim).

**Comment by superjax** [comment]
I just added a BSD-3 License to our stuff.  The intention is to be compatible with an MIT license.

We are in the middle of a pull request  #103, which will make the distinction between BreezySTM32 (our hardware layer), which is licensed under GPL and ROSflight itself, so there is less ambiguity about licensing.
