### ISSUE TITLE
PARAM_MAX_COMMAND not converted to float

### ISSUE THREAD

**Issue by dpkoch** [byu-magicc/ROSflight#127]
It looks like PARAM_MAX_COMMAND got missed when everything got converted over to float; it's currently an int with default value of 1000. So it's probably doing nothing. I assume it should be a float with default value of 1.0? @superjax if you agree then I'm happy to make the switch.

**Comment by superjax** [comment]
I don't think that MAX_COMMAND is used anywhere.  If that's the case, then we should just removed it.  (I guess then, what is the point of anti-windup?)

**Comment by superjax** [comment]
Sorry, my mistake, it is used in the controller.  It should definitely be a float.   I think even a value of 1.0 won't do anything except in the most extreme cases, and I'm not sure what would happen to stability if we actually reached saturation limits....  Probably something I should test before release.
