### ISSUE TITLE
Airspeed sensor error

### ISSUE THREAD

**Issue by srogers4** [byu-magicc/ROSflight#140]
![image](https://cloud.githubusercontent.com/assets/23121516/25447818/cc9a60b6-2a73-11e7-980b-494e4b706058.png)
Here is the plot from our test flight on 4/26/17. There are issues with the airspeed sensor regarding differential pressure.

**Comment by superjax** [comment]
Sorry about this guys, this sensor is really a pain.

**Comment by superjax** [comment]
Oh, I think I know what this is.
