### ISSUE TITLE
Streamline Mux Logic

### ISSUE THREAD

**Issue by superjax** [byu-magicc/ROSflight#26]
1. [ ] Update flow diagram pdf to represent what is going on in the code
2. [ ] Redesign flow, knowing how it is supposed to work
3. [ ] Re-code mux.c

**Comment by dpkoch** [comment]
@superjax I've started working on this with my rc_refactor branch, just so you're aware. I'll let you know once I've got something to show

**Comment by superjax** [comment]
@dpkoch wrote some awesome stuff and it got merged in #120.
