### ISSUE TITLE
Arming Logic

### ISSUE THREAD

**Issue by superjax** [byu-magicc/ROSflight#28]
We should re-code mode.c to be a state machine, rather than a series of if and else statements

**Comment by superjax** [comment]
I looked into doing this, and I think that it would be more confusing that the if statements that we have.  There really are only four states.

Anyway, I think that it's fine as is.  I'm wondering if @dpkoch had insight that I don't have.

**Comment by dpkoch** [comment]
#72 has a hotfix for issue where autopilot would arm on initialization if RC was not present. This issue should address this in a more sophisticated fashion.

**Comment by superjax** [comment]
A lot of cleanup happened in #103 with the RC abstraction.  I think that we might still get more clarity from a state machine matrix approach, but until then, I think this is pretty good.
