### ISSUE TITLE
Change it to Fixed Wing?

### ISSUE THREAD

**Issue by dallinbriggs** [byu-magicc/ROSflight#93]
How do you change ROSflight to control a fixed wing UAV?

**Comment by superjax** [comment]
It's generally the following parameter changes.
```
FIXED_WING = true
MIXER = 5'
ARM_STICKS = false
ARM_SPIN_MOTORS = false
```

You will also probably want to check the following parameters for your setup:
```
ELEVATOR_REV
AILERON_REV
RUDDER_REV
ARM_CHANNEL
```
